const conf = {
  appwriteUrl: String(import.meta.env.VITE_APPWRITE_URL),
  projectId: String(import.meta.env.VITE_PROJECT_ID),
  databaseId: String(import.meta.env.VITE_DATABASE_ID),
  collactionId: String(import.meta.env.VITE_COLLACTION_ID),
  profileCollactionId: String(import.meta.env.VITE_PROFILE_ID),
  heroCollactionId: String(import.meta.env.VITE_HERO_ID),
  aboutCollactionId: String(import.meta.env.VITE_ABOUT_ID),
  philosophyCollactionId: String(import.meta.env.VITE_ABOUT_PHILOSOPHY_ID),
  awardsCollactionId: String(import.meta.env.VITE_ABOUT_AWARDS_ID),
  herobannerCollactionId: String(import.meta.env.VITE_ABOUT_HERO_BANNER_ID),
  menuherobannerCollactionId: String(import.meta.env.VITE_MENU_HERO_BANNER_ID),
  culinaryCollactionId: String(import.meta.env.VITE_MENU__CULINARY_ID),
  culinaryiconeCollactionId: String(import.meta.env.VITE_MENU__CULINARY_ICONE_ID),
  offerCollactionId: String(import.meta.env.VITE_MENU__OFFER_ID),
  offerlistCollactionId: String(import.meta.env.VITE_MENU__OFFER_LIST_ID),
  galleryCollactionId: String(import.meta.env.VITE_GALLERY_ID),
  galleryherobannerCollactionId: String(import.meta.env.VITE_GALLERY_HERO_BANNER_ID),
  contectCollactionId: String(import.meta.env.VITE_CONTECT_ID),
  addressCollactionId: String(import.meta.env.VITE_ADDERSS_ID),
  contectheroCollactionId: String(import.meta.env.VITE_CONTECT_HERO_ID),
  reservetableCollactionId: String(import.meta.env.VITE_RESERVE_TABLE_ID),
  settingCollactionId: String(import.meta.env.VITE_SETTING_ID),
  socialiconeCollactionId: String(import.meta.env.VITE_SOCIAL_ICONE_ID),
  chefCollactionId: String(import.meta.env.VITE_CHEF_ID),
  bucketId: String(import.meta.env.VITE_BUCKET_ID),
};

export default conf;
